image: maven:3.8-openjdk-11
default:
  tags:
    - dockerRunner

stages:
    - test

Demo test:
  stage: test
  script:
    - mvn clean test
    - mvn allure:report

  artifacts:
    paths:
    - allure-results/*
